development:
  cloud_name: hvhknizcd
  api_key: '123526499612984'
  api_secret: "Xe_gUjwrdIz-qM4-36BcKDn-Uxw"
  enhance_image_tag: true
  static_file_support: false
  secure: true
production:
  cloud_name: hvhknizcd
  api_key: '123526499612984'
  api_secret: "Xe_gUjwrdIz-qM4-36BcKDn-Uxw"
  enhance_image_tag: true
  static_file_support: true
  secure: true
test:
  cloud_name: hvhknizcd
  api_key: '123526499612984'
  api_secret: "Xe_gUjwrdIz-qM4-36BcKDn-Uxw"
  enhance_image_tag: true
  static_file_support: false
  secure: true
